# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-SaltedHash
version:      0.01
version_from: lib/Crypt/SaltedHash.pm
installdirs:  site
requires:
    Digest:                        1.10
    MIME::Base64:                  3.05

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
